name: keepalive

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0,12 * * * *"
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
  
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto-commit keeps alive
        run: |
          git config --local user.email "abc@gmail.com"
          git config --local user.name "${{ github.actor }}"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "a commit per 15 minutes to keep webapp alive"
          git push
